name: Deploy Python app to Azure Web App - azurekhuging

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write       # Required for requesting JWT
      contents: read        # Required for actions/checkout

    steps:
      # 1️⃣ Checkout your repo
      - uses: actions/checkout@v4

      # 2️⃣ Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D199A508FEF4B588BA1BB6F848ED9DC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FCC59FB43096456F9647FBBDCAC38BD0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EFC58B8518F548359C6707B5D64EA14E }}

      # 3️⃣ Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'azurekhuging'
          slot-name: 'Production'
